const blogList = [
  {
    id:1,
    title: "20 Fun Facts About JavaScript",
    author: "John Doe",
    body:"some",
    date: "Feb 1, 2023",
  },
  {
    id:2,
    title: "Why You're Failing at Music",
    author: "Jane Smith",
    body:"some",
    date: "May 10, 2023",
  },
  {
    id:3,
    title: "Meet the Steve Jobs of Indian Industry",
    author: "Helmfrid Varvara",
    body:"Meet the Steve Jobs of Indian Industry Meet the Steve Jobs of Indian Industry Meet the Steve Jobs of Indian Industry vMeet the Steve Jobs of Indian Industry Meet the Steve Jobs of Indian Industry",
    date: "June 26, 2023",
  },
  {
    id:4,
    title: "The Ultimate Guide to Visit",
    author: "Karl Elpis",
    body:"some",
    date: "Apr 21, 2023",
  },
  {
    id:5,
    title: "How to Get More Results Out of Your Weather",
    author: "Uliana Laura",
    body:"some",
    date: "Jan 19, 2023",
  },
  {
    id:6,
    title: "How Much Should You Be Spending on AQI?",
    author: "Shiori Aod",
    body:"some",
    date: "May 29, 2023",
  },
  {
    id:7,
    title: "The Worst Advice We've Ever Heard About Budget",
    author: "Fernanda Agustín",
    body:"some",
    date: "Apr 8, 2023",
  },
  {
    id:8,
    title: "8 Effective Coding Elevator Pitches",
    author: "Tadashi Osgar",
    body:"some",
    date: "Nov 18, 2023",
  },
  {
    id:9,
    title: "The History of Adobe",
    author: "Zacchaeus Bill",
    body:"some",
    date: "Sept 25, 2023",
  },
];
export default blogList;
